Cleanup and rename
pulsar-edit/package-generator pull request #1
Opened 2022-12-01 14:49 UTC by Sertonix

This pull request does the following:
- remove unused `.md` files
- removed badges from readme
- change repository url
- rename/remove `Atom` references

2022-12-02 00:59 UTC, confused-Techie requested changes
This overall looks fantastic, but added one change, since we might as well be thorough on here. Thanks for contributing!

2022-12-02 00:59 UTC, confused-Techie commented on README.md
>  Generates and opens a new sample package, language, or syntax theme in Atom.
```suggestion
Generates and opens a new sample package, language, or syntax theme in Pulsar.
```

2022-12-02 07:11 UTC, confused-Techie approved these changes
Fantastic, thanks for getting on those changes. This looks rad!

2022-12-10 23:39 UTC, Sertonix commented
Close in favor of #2

2022-12-10 23:39 UTC, closed without merging

2022-12-11 03:01 UTC, confused-Techie commented
@Sertonix we don't have to close this one if you don't want. If the PR on the main editor was accepted I was going to merge this one, then right after #2, if you don't mind we can leave it closed, but didn't want to discount the contribution you've made to this repo

2022-12-11 09:34 UTC, Sertonix commented
It is mentioned in the pull request so this is not needed